package rules;

import touristApp.model.*;

declare function calculateDiscountedPrice( double price, double discount )
    return (price * (1 - discount));
end

rule "Excursion discount for multiple people"
when
    $reservation : Reservation( )
    $excursions : List( size >= 2 ) from $reservation.getExcursions()
then
    double totalExcursionPrice = 0.0;
    for ( Excursion excursion : $excursions ) {
        totalExcursionPrice += excursion.getPrice();
    }
    
    double discount = 0.1;
    double discountedExcursionPrice = totalExcursionPrice * (1 - discount);
    
    $reservation.setTotalPrice($reservation.getArrangement().getPrice()* $reservation.getNumberOfPeople() + discountedExcursionPrice* $reservation.getNumberOfPeople());
    
    update($reservation);
end

rule "Excursion discount for price over 3000"
when
    $reservation : Reservation( )
    $excursions : List( ) from $reservation.getExcursions()
then
    
    double totalReservationPrice = 0.0;
    for ( Excursion excursion : $excursions ) {
        double totalExcursionPrice = 0.0;
        totalExcursionPrice += excursion.getPrice() * $reservation.getNumberOfPeople();
        if ( totalExcursionPrice > 3000 ) {
            double discount = 0.05;
            double discountedExcursionPrice = totalExcursionPrice * (1 - discount);
            totalReservationPrice+=discountedExcursionPrice
            
        } else {
            totalReservationPrice+= excursion.getPrice() * $reservation.getNumberOfPeople()
        }
    }
    
   $reservation.setTotalPrice($reservation.getArrangement().getPrice()* $reservation.getNumberOfPeople() + totalReservationPrice);
    
    update($reservation);
end

rule "Excursion discount for price over 2000 and the excursion belongs to the Historical Content category"
when
    $reservation : Reservation( )
    $excursions : List( ) from $reservation.getExcursions()
then
    
    double totalReservationPrice = 0.0;
    for ( Excursion excursion : $excursions ) {
        double totalExcursionPrice = 0.0;
        totalExcursionPrice += excursion.getPrice() * $reservation.getNumberOfPeople();
        if ( totalExcursionPrice > 2000 && excursion.getType==ExcursionType.HISTORICAL) {
            double discount = 0.07;
            double discountedExcursionPrice = totalExcursionPrice * (1 - discount);
            totalReservationPrice+=discountedExcursionPrice
            
        } else {
            totalReservationPrice+= excursion.getPrice() * $reservation.getNumberOfPeople()
        }
    }
    
   $reservation.setTotalPrice($reservation.getArrangement().getPrice()* $reservation.getNumberOfPeople() + totalReservationPrice);
    
    update($reservation);
end

